/**
 * Tests for scripts/statusline-classifier.js
 *
 * Uses node's built-in assert. Run with: node tests/unit/classifier.test.js
 */
import assert from 'assert';
import { writeFileSync, mkdtempSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { classifyStatusLine, extractScriptPath } from '../../scripts/statusline-classifier.js';

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failed++;
  }
}

// --- Create temp dir with fixture scripts ---
const tmp = mkdtempSync(join(tmpdir(), 'statusline-classifier-'));
const placeholderPath = join(tmp, 'placeholder.js');
const wrappedPath = join(tmp, 'wrapped.js');
const customPath = join(tmp, 'custom.js');
const cliOnlyPath = join(tmp, 'statusline-CLI-only.js');
const legacyStandalonePath = join(tmp, 'statusline-standalone.js');
const forwarderPath = join(tmp, 'hook-forwarder.js');

writeFileSync(cliOnlyPath,
  '#!/usr/bin/env node\n// CLI-only statusline\nconsole.log("cli-only");\n'
);
writeFileSync(legacyStandalonePath,
  '#!/usr/bin/env node\n// Legacy standalone statusline\nconsole.log("standalone");\n'
);
writeFileSync(placeholderPath,
  '#!/usr/bin/env node\n// Standalone Claude Code statusline — based on statusline-script.md\n// Temporary until rh-telemetry is installed and configured.\nconsole.log("hi");\n'
);
writeFileSync(wrappedPath,
  '#!/usr/bin/env node\n// rh-telemetry:wrapped /some/original/path.js\n// Generated by rh-telemetry.\nconsole.log("wrapped");\n'
);
writeFileSync(customPath,
  '#!/usr/bin/env node\n// My totally custom statusline that does its own thing\nconsole.log("custom");\n'
);
writeFileSync(forwarderPath,
  '#!/usr/bin/env node\n// hook-forwarder stub\n'
);

console.log('statusline-classifier tests:\n');

// --- extractScriptPath ---
test('extractScriptPath: quoted absolute path', () => {
  assert.strictEqual(
    extractScriptPath('node "C:/Users/user/.claude/scripts/statusline.js"'),
    'C:/Users/user/.claude/scripts/statusline.js'
  );
});

test('extractScriptPath: unquoted path', () => {
  assert.strictEqual(
    extractScriptPath('node C:/Users/user/.claude/scripts/statusline.js'),
    'C:/Users/user/.claude/scripts/statusline.js'
  );
});

test('extractScriptPath: command with args after script', () => {
  assert.strictEqual(
    extractScriptPath('node /abs/path/hook-forwarder.js status'),
    '/abs/path/hook-forwarder.js'
  );
});

test('extractScriptPath: no js file returns null', () => {
  assert.strictEqual(extractScriptPath('echo hello'), null);
});

test('extractScriptPath: empty/null input', () => {
  assert.strictEqual(extractScriptPath(''), null);
  assert.strictEqual(extractScriptPath(null), null);
  assert.strictEqual(extractScriptPath(undefined), null);
});

// --- classifyStatusLine ---
test('classify: missing statusLine', () => {
  const result = classifyStatusLine({});
  assert.strictEqual(result.class, 'missing');
  assert.strictEqual(result.command, '');
});

test('classify: missing settings entirely', () => {
  const result = classifyStatusLine(null);
  assert.strictEqual(result.class, 'missing');
});

test('classify: telemetry forwarder command', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${forwarderPath}" status` },
  });
  assert.strictEqual(result.class, 'telemetry');
});

test('classify: telemetry forwarder without quotes', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node ${forwarderPath} status` },
  });
  assert.strictEqual(result.class, 'telemetry');
});

test('classify: hook-forwarder WITHOUT status arg is NOT telemetry', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node ${forwarderPath}` },
  });
  assert.notStrictEqual(result.class, 'telemetry');
});

test('classify: wrapped script detected', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${wrappedPath}"` },
  });
  assert.strictEqual(result.class, 'telemetry-wrapper');
});

test('classify: placeholder script detected', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${placeholderPath}"` },
  });
  assert.strictEqual(result.class, 'placeholder');
  assert.strictEqual(result.reason, 'legacy fallback script detected');
});

test('classify: CLI-only statusline → cli-only (auto-upgrade target)', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${cliOnlyPath}"` },
  });
  assert.strictEqual(result.class, 'cli-only');
  assert.ok(result.reason.includes('CLI-only'));
});

test('classify: legacy statusline-standalone.js → cli-only (auto-upgrade target)', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${legacyStandalonePath}"` },
  });
  assert.strictEqual(result.class, 'cli-only');
});

test('classify: custom script → unknown-custom', () => {
  const result = classifyStatusLine({
    statusLine: { command: `node "${customPath}"` },
  });
  assert.strictEqual(result.class, 'unknown-custom');
  assert.ok(result.scriptPath);
});

test('classify: script path that does not exist → unknown-custom', () => {
  const result = classifyStatusLine({
    statusLine: { command: 'node /totally/nonexistent/path.js' },
  });
  assert.strictEqual(result.class, 'unknown-custom');
  assert.strictEqual(result.reason, 'script file not readable');
});

test('classify: command with no script file → unknown-custom', () => {
  const result = classifyStatusLine({
    statusLine: { command: 'echo "just a string"' },
  });
  assert.strictEqual(result.class, 'unknown-custom');
  assert.strictEqual(result.scriptPath, null);
});

// --- Cleanup ---
rmSync(tmp, { recursive: true, force: true });

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
